# -*- coding: utf-8 -*-
{
    'name': 'ФГВ: Продаж активів',
    'summary': '''ФГВ: Продаж активів''',
    'description': '''ФГВ: Продаж активів''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Sale',
    'depends': [
        'base',
        'mail',
        'web',
        'contacts',
        'dgf_insolvent',
        'dgf_auction_base',
        'dgf_auction_sale',
    ],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'security/groups.xml',
        'security/security_rules.xml',
        'security/ir.model.access.csv',
        # 'views/dgf_sale_proposal_views.xml',
        'views/dgf_sale_base_menus.xml',
        # 'views/res_config_settings.xml',

    ],
    'demo': [],
    'qweb': [],
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
    'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
