# -*- coding: utf-8 -*-
{
    'name': 'Аукціони: продаж майна у ВП',
    'summary': '''СЕТАМ: Аукціони з продажу арештованого майна.''',
    'description': '''СЕТАМ: Аукціони з продажу арештованого майна.''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Auction',
    'depends': [
        'base',
        'mail',
        'base_automation',
        'dgf_iap_provider',
        'dgf_auction_base',
        'dgf_enforcement',
        'agreement',
        ],
    'external_dependencies': {'python': ['beautifulsoup4'], 'bin': []},
    'data': [
        # 'data/cron.xml',
        'data/data.xml',
        # 'data/dgf_procedure_stage.xml',
        # 'security/groups.xml',
        # 'security/security_rules.xml',
        # 'security/ir.model.access.csv',
        'views/dgf_enforcement_views.xml',
        'views/dgf_procedure_views.xml',
        # 'views/dgf_procedure_lot_views.xml',
        'views/dgf_procedure_menus.xml',
        # 'views/res_config_settings.xml',
    ],
    'demo': [],
    'qweb': [],
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
    'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
