# -*- coding: utf-8 -*-
{
    'name': 'DGF: Sale Proposal',
    'summary': '''DGF Sale Proposal module''',
    'description': '''DGF Sale Proposal module''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Sale',
    'depends': [
        'base',
        'mail',
        'web',
        'contacts',
        'dgf_insolvent',
        'l10n_ua_classifier',
        'dgf_asset'],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        # 'security/groups.xml',
        # 'security/security_rules.xml',
        # 'views/res_config_settings.xml',
        'security/ir.model.access.csv',
        # 'views/ir_attachment_views.xml',
        'views/dgf_sale_proposal_views.xml',
        'views/dgf_sale_proposal_menus.xml',
    ],
    # 'demo': [],
    # 'qweb': [],
    # 'post_load': None,
    # 'pre_init_hook': None,
    # 'post_init_hook': None,
    # 'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
