# -*- coding: utf-8 -*-
{
    'name': 'ФГВФО: Активи банків',
    'summary': '''ФГВФО: модуль "Активи банків"''',
    'description': '''ФГВФО: модуль "Активи банків"''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Assets',
    'depends': [
        'base',
        'mail',
        'contacts',
        'dgf_base_stage',
        # 'l10n_ua_address',
        # 'dgf_insolvent',
        ],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'security/groups.xml',
        'security/security_rules.xml',
        # 'views/res_config_settings.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/dgf_asset_register_type.xml',
        'data/dgf_asset_category.xml',
        'data/base_stage.xml',
        'data/mail_data.xml',
        'views/dgf_asset_category_views.xml',
        'views/ir_attachment_views.xml',
        'views/dgf_asset_base_views.xml',
        'views/dgf_asset_fixed_views.xml',
        # 'views/dgf_asset_loan_views.xml',
        'views/dgf_asset_sale_import_views.xml',
        'views/dgf_asset_sale_transaction_views.xml',
        'views/res_partner_views.xml',
        'views/dgf_asset_menus.xml',
    ],
    # 'demo': [],
    # 'qweb': [],
    # 'post_load': None,
    # 'pre_init_hook': None,
    # 'post_init_hook': None,
    # 'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
