# -*- coding: utf-8 -*-
{
    'name': 'Аукціони. Базовий модуль',
    'summary': '''ФГВ: Базовий модуль аукціонів''',
    'description': '''ФГВ: Базовий модуль аукціонів''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Auction',
    'depends': [
        'base',
        'base_automation',
        'mail',
        'agreement',
        'attachment_category',
        'dgf_iap_provider',
        ],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'data/data.xml',
        'security/groups.xml',
        # 'security/security_rules.xml',
        'security/ir.model.access.csv',
        'views/ir_attachment_views.xml',
        'views/dgf_procedure_views.xml',
        'views/dgf_procedure_lot_views.xml',
        'views/agreement.xml',
        'views/dgf_procedure_templates.xml',
        'views/res_config_settings.xml',
        'views/dgf_procedure_menus.xml',
    ],
    'demo': [],
    'qweb': [],
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
    'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
