# -*- coding: utf-8 -*-
{
    'name': 'Аукціони: продаж активів',
    'summary': '''ФГВ: Аукціони з продажу активів на Prozorro.Sale.''',
    'description': '''ФГВ: Аукціони з продажу активів на Prozorro.Sale.''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Auction',
    'depends': [
        'base',
        'mail',
        # 'contacts', # чи потрібно???
        'base_automation',
        'dgf_iap_provider',
        'dgf_auction_base',
        'agreement',
        'agreement_dgf',
        # 'dgf_document',
        # 'l10n_ua_classifier'
        ],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'data/cron.xml',
        'data/data.xml',
        'data/dgf_procedure_stage.xml',
        # 'security/groups.xml',
        # 'security/security_rules.xml',
        # 'security/ir.model.access.csv',
        'views/dgf_procedure_views.xml',
        'views/dgf_procedure_lot_views.xml',
        'views/agreement.xml',
        # 'views/dgf_asset_views.xml',
        # 'views/stat_classifier_views.xml',
        # 'ir_attachment_views.xml',
        'views/dgf_procedure_menus.xml',
        # 'views/res_config_settings.xml',
    ],
    'demo': [],
    'qweb': [],
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
    'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
