# -*- coding: utf-8 -*-
{
    'name': 'ФГВ: Користування майном',
    'summary': '''ФГВ: Модуль користування майном''',
    'description': '''ФГВ: Модуль оренди''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Rent',
    'depends': [
        'base',
        'mail',
        'web',
        'contacts',
        'dgf_insolvent',
        'dgf_asset_base',        
        'dgf_auction_base',
        'dgf_asset_lot',
        'dgf_auction_sale',
        'agreement',
        'agreement_dgf',
        'l10n_ua_classifier'],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'security/groups.xml',
        # 'security/security_rules.xml',
        # 'views/res_config_settings.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        # 'views/product_view.xml',
        # 'views/ir_attachment_views.xml',
        # 'views/dgf_asset_views.xml',
        'views/dgf_procedure_lot_asset_views.xml',
        'views/dgf_procedure_lot_views.xml',
        'views/agreement.xml',
        'views/dgf_rent_menus.xml',
    ],
    # 'demo': [],
    # 'qweb': [],
    # 'post_load': None,
    # 'pre_init_hook': None,
    # 'post_init_hook': None,
    # 'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
