# -*- coding: utf-8 -*-
{
    'name': 'DGF Configuration',
    'summary': '''Main DGF Configuration module''',
    'description': '''Main DGF Configuration module''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.0.1',
    'category': 'Liquidation/Configuration',
    # any module necessary for this one to work correctly
    'depends': [
        'base_automation',
        'base_import',
        'auth_password_policy',
        'auth_password_policy_signup',
        # 'currency_rate_update',
        # 'base_iban',
        # 'account',
        # 'calendar',
        # 'l10n_ua',
        'l10n_ua_state',
        'web_responsive',
        'web_sheet_full_width',
        'web_refresher',
        'web_dialog_size',
        'web_search_panel_hide_show',
        # 'web_tree_many2one_clickable',
        'mass_editing',
        'auditlog',
        # 'auto_backup',
        # 'report_py3o',
    ],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [],
    # 'demo': [],
    # 'qweb': [],
    # 'post_load': None,
    # 'pre_init_hook': None,
    # 'post_init_hook': None,
    # 'uninstall_hook': None,
    'auto_install': False,
    'application': False,
    'installable': True,
}
