# -*- coding: utf-8 -*-
{
    'name': 'DGF: Documents',
    'summary': '''DGF documents module''',
    'description': '''DGF documents module''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Documents',
    'depends': [
        'base',
        'mail',
        'web',
        'contacts',
        'hr',
        'hr_contract'],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        # 'views/res_config_settings.xml',
        'data/dgf.document.type.csv',
        'data/hr.department.csv',
        'views/dgf_document_category_views.xml',
        'views/dgf_document_type_views.xml',
        'views/hr_department_views.xml',
        'views/ir_attachment_views.xml',
        'views/dgf_document_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/dgf_document_menus.xml',
    ],
    # 'demo': [],
    # 'qweb': [],
    # 'post_load': None,
    # 'pre_init_hook': None,
    # 'post_init_hook': None,
    # 'uninstall_hook': None,
    'auto_install': False,
    'application': True,
    'installable': True,
}
