# -*- coding: utf-8 -*-
{
    'name': 'Аукціони: бридж Документи',
    'summary': '''Аукціони: технічний модуль доповнення аукціонів рішеннями УКО.''',
    'description': '''Аукціони: технічний модуль доповнення аукціонів рішеннями УКО.''',
    'author': 'DGF',
    'website': 'https://fg.gov.ua',
    'license': 'AGPL-3',
    'version': '14.0.0.1',
    'category': 'Liquidation/Auction',
    'depends': [
        'dgf_auction_base',
        'dgf_auction_sale',
        'dgf_document',
        ],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'views/dgf_procedure_views.xml',
        'views/dgf_procedure_lot_views.xml',
        # 'views/res_config_settings.xml',
    ],
    'demo': [],
    'qweb': [],
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
    'uninstall_hook': None,
    'auto_install': True,
    'application': False,
    'installable': True,
}
